### ISSUE TITLE
Startup Crash on Forge Server because of EntityRenderer

### ISSUE THREAD

**Issue by muqsit-0010** [OneLemonyBoi/MiniUtilities#32]
MC: 1.6.5
Forge: 36.1.18
Mini Utilities: miniutilities-1.1.1.jar

**To Reproduce**
1. Setup Forge Server
2.  Install Mini Utilities
3.  Run the server

**Details**
Client side EntityRenderer is being used without a side check, which is making the mod crash the server on startup.

**Crash Report attached below**
[crash-2021-05-17_03.33.49-fml.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/6490920/crash-2021-05-17_03.33.49-fml.txt)

**Comment by OneLemonyBoi** [comment]
fixed!

**Comment by muqsit-0010** [comment]
Still crashing with the latest miniutilities-1.1.2.jar
@OneLemonyBoi
