### ISSUE TITLE
Crash and error on server 

### ISSUE THREAD

**Issue by GnomTocha** [OneLemonyBoi/MiniUtilities#60]
It is impossible to remove the mechanical placer without using the commands and the spikes crash the server.
forge-1.16.5-36.1.23;
miniutilities-1.1.3;
[debug.log](https://github.com/OneLemonyBoi/MiniUtilities/files/6644431/debug.log)
[latest.log](https://github.com/OneLemonyBoi/MiniUtilities/files/6644432/latest.log)
[crash-2021-06-13_21.10.09-server.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/6644433/crash-2021-06-13_21.10.09-server.txt)
Playback error: https://youtu.be/PMSu9UFkdGc

**Comment by OneLemonyBoi** [comment]
fixed in dev

**Comment by Elfinlocks** [comment]
This issue is still present, can this in dev version be released?

**Comment by OneLemonyBoi** [comment]
Currently preparing for a final release as soon as 1.17 forge releases.
Ironing out bugs in dev as well, this is fixed in dev alr.

**Comment by Elfinlocks** [comment]
Is there any chance of it releasing for 1.16.5?

**Comment by OneLemonyBoi** [comment]
Yeah, I’m just waiting for 1.17

**Comment by OneLemonyBoi** [comment]
hey @Elfinlocks this has released in 1.16.5, i decided to not port to 1.17 and skip it
